### ISSUE TITLE
After re-encryption, all DMI data written to the machine is INVALID.

### ISSUE THREAD

**Issue by cbbos** [Shmurkio/LenovoDMIDecryptor#1]

**Comment by Shmurkio** [comment]
You have to make sure to not change the length of each "string". The structure of each data field is a 14 byte data field separator "55570ec26911564ca48a9824ab43", a 3 Byte identifier for the data type, a 7 byte buffer consisting of 00, and then the data string. If you want to change the length you have to adjust the buffer length otherwise the data will become invalid. Make sure not to overwrite the separator or change the data type identifier either. Also update the data in the second LENV block and don't change the second LENV offset even if you change the size of strings in the first LENV block. Your data will be valid if you follow this.

Edit: the buffer of the Windows Key is not 7 bytes of 00, it is "00000000000000010000000000000001000000000000001d000000".

**Comment by cbbos** [comment]
Yes everything is going in the right direction.
I only change the SN part. and stays the same length.. when I write back to the chip. All dmi data in the BIOS is displayed as invalid.
I've tried encryption/no encryption. All are invalid.
Even if only one byte is changed 32(2) to 33(3)

**Comment by Puntolimpio** [comment]
SAME HERE.Change model IdeaPad 3 14IIL (49 64 65 61 50 61 64 20 33 20 31 34 49 49 4C) to IdeaPad 3 1**5**IIL (49 64 65 61 50 61 64 20 33 20 31 3**5** 49 49 4C)

**Comment by Shmurkio** [comment]
Fixed it. It was a checksum error. Tested it on a few devices, all data will be valid now.
